name: 01_Service_Deploy

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

  workflow_dispatch:
    branches: ["main", "develop"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  install-build-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'install-build-test'
      
  release-to-development:
    if: github.ref == 'refs/heads/develop'
    needs: install-build-test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment:
      name: development
    steps:
      - run: exit 99 #echo 'release-to-development'
      - run: echo "::set-output name=status::success"

  release-to-staging:
    if: github.ref == 'refs/heads/main'
    needs: install-build-test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment:
      name: staging
    steps:
      - run: echo 'release-to-staging'
      - run: echo "::set-output name=status::success"

  check-success:
    needs: [release-to-development, release-to-staging]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [release-to-development, release-to-staging]
    steps:
      - name: Check success of ${{ matrix.job }}
        run: |
          if [ "${{ needs[matrix.job].result }}" != "success" ]; then
            exit 1
          fi
        continue-on-error: true

  create-sentry-release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs:
      - release-to-development
      - release-to-staging
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Sentry release
        if: needs.release-to-development.outputs.status == 'success' || needs.release-to-staging.outputs.status == 'success'
        run: echo 'getsentry/action-release@v1'