name: 01_Service_Deploy

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

  workflow_dispatch:
    branches: ["main", "develop"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  install-build-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'install-build-test'
      
  release-to-development:
    if: github.ref == 'refs/heads/develop'
    needs: install-build-test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment:
      name: development
    steps:
      - name: Set ENV name for Sentry
        run: echo "SENTRY_ENV_NAME=staging" >> "$GITHUB_ENV"

  release-to-staging:
    if: github.ref == 'refs/heads/main'
    needs: install-build-test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment:
      name: staging
    steps:
      - name: Set ENV name for Sentry
        run: echo "SENTRY_ENV_NAME=staging" >> "$GITHUB_ENV"

  check-success:
    needs: [release-to-development, release-to-staging]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [release-to-development, release-to-staging]
    steps:
      - name: Check success of ${{ matrix.job }}
        run: |
          if [ "${{ needs[matrix.job].result }}" != "success" ]; then
            exit 1
          fi
        continue-on-error: true

  create-sentry-release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: check-success
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: $SENTRY_ENV_NAME